### ISSUE TITLE
Cycles in recipes

### ISSUE THREAD

**Issue by Luke100000** [Slomaxonical-907/Architects-Palette-Fabric#24]
We got a stackoverflow when checking recipes, took me a while to track them to the recipe advancements.
`chiseled_iron_ore_bricks_stonecutting` was the one crashing it specifically, but I checked the other files, they all require itself. Is this intended?

The recursion happens here:
```
	at net.minecraft.server.PlayerAdvancements.ensureVisibility(PlayerAdvancements.java:348)
	at net.minecraft.server.PlayerAdvancements.ensureVisibility(PlayerAdvancements.java:344)
	at net.minecraft.server.PlayerAdvancements.ensureVisibility(PlayerAdvancements.java:348)
	at net.minecraft.server.PlayerAdvancements.ensureVisibility(PlayerAdvancements.java:344)
	at net.minecraft.server.PlayerAdvancements.ensureVisibility(PlayerAdvancements.java:348)
```

Which ensures the visibility of parent and childrens, which is where the recursion happens.

**Comment by Luke100000** [comment]
Other mods also crash, same self reference. I assume it has a reason and Architects Palette is not at fault. Any idea on why it may cause troubles?

**Comment by Slomaxonical-907** [comment]
I'm guessing what you mean by requiring itself is the "requirements"  in the advancements. If so: 
![image](https://user-images.githubusercontent.com/77751655/183655717-728de9d9-be8e-490d-b41d-26ced03002d4.png)
I'm using vanilla's recipe generators, dunno what could be causing this honestly.

**Comment by Luke100000** [comment]
I see. Considering vanilla also does this I'm certain it's an error with another mod messing with advancements. Thanks for your response!
